### PR TITLE
allow for defining optional orm methods

### PR DESCRIPTION
**Pull request by gotjoshua**
## This PR contains:
 - IMPROVED typings

## Describe the problem you have without this PR
#2304

### CODE REVIEW

**Comment by pubkey** [comment]
Hi.
As far as I understand this PR would make all ORM-functions optional.
This means when you have strict-mode enabled, you would have to add a null-check each time the function is used.

**Comment by gotjoshua** [comment]
> As far as I understand this PR would make all ORM-functions optional.
> This means when you have strict-mode enabled, you would have to add a null-check each time the function is used.

ouch. I am not a TS expert at all yet, and actually (as I mentioned on [the Issue](https://github.com/pubkey/rxdb/issues/2304)), I assume that there must be a better way to declare the types for the prototype overrides in a plugin. Do you have any advice or examples posted about that?

**Comment by pubkey** [comment]
I have not solved that problem which is why all types are always exported, even with the custom build where only some functions are allowed, depending on which plugin is used.
Why do you have to set this optional? Isn't `getHistoryMap` always available when your plugin is used?

**Comment by gotjoshua** [comment]
well its available, but TS complains that it is missing, when I define the other orm methods for my DocType.

**Comment by pubkey** [comment]
Sorry for the late answer. Have you fixed this? I think you need to use `as any` and then you can hack your type together.

**Comment by gotjoshua** [comment]
Well I didn't solve it, but I'm also not trying actively. I think it is clear that this pull request doesn't make sense as we don't need to start littering code with null checks all over.
When I get back to it, i'll try out the `as any` hack, but I'll go ahead and close this un-merged...

**Pull request closed without merging**
